# Generated by Django 4.2.16 on 2026-08-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_new_security_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, unique=True)),
                ('os', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('username', models.CharField(max_length=100)),
                ('agent_version', models.CharField(max_length=20)),
                ('last_seen', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Endpoint Status',
                'verbose_name_plural': 'Endpoint Statuses',
                'ordering': ['hostname'],
            },
        ),
    ]
