# Generated by Django 4.2.16 on 2026-08-14 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_endpointstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointstatus',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='endpointstatus',
            name='wol_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PowerActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('operation', models.CharField(choices=[('power_on', 'Power On (WoL)'), ('shutdown', 'Shutdown'), ('restart', 'Restart')], max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_logs', to='dashboard.endpointstatus')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='power_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Power Action Log',
                'verbose_name_plural': 'Power Action Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EndpointCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(choices=[('shutdown', 'Shutdown'), ('restart', 'Restart')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('executing', 'Executing'), ('success', 'Success'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result_message', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='dashboard.endpointstatus')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='power_commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Endpoint Command',
                'verbose_name_plural': 'Endpoint Commands',
                'ordering': ['-created_at'],
            },
        ),
    ]
