# Generated by Django 4.2.16 on 2026-08-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_endpointstatus_mac_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointreport',
            name='s3_object_key',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
