# Generated by Django 4.2.16 on 2026-09-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_endpointreport_s3_object_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='endpointreport',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='endpointreport',
            constraint=models.UniqueConstraint(condition=models.Q(('s3_object_key__isnull', False), models.Q(('s3_object_key', ''), _negated=True)), fields=('s3_object_key',), name='unique_s3_object_key_when_set'),
        ),
        migrations.AddConstraint(
            model_name='endpointreport',
            constraint=models.UniqueConstraint(condition=models.Q(('s3_object_key', '')), fields=('hostname', 'report_date'), name='unique_hostname_date_when_no_s3_key'),
        ),
    ]
