# Generated by Django 4.2.16 on 2026-09-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_endpointreport_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointstatus',
            name='antivirus_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endpointstatus',
            name='cpu_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endpointstatus',
            name='disk_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endpointstatus',
            name='firewall_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endpointstatus',
            name='health_score',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='endpointstatus',
            name='health_status',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('critical', 'Critical')], default='healthy', max_length=20),
        ),
        migrations.AddField(
            model_name='endpointstatus',
            name='last_health_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endpointstatus',
            name='memory_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endpointstatus',
            name='process_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='endpointstatus',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='endpointstatus',
            index=models.Index(fields=['mac_address'], name='dashboard_e_mac_add_b54ffc_idx'),
        ),
        migrations.AddIndex(
            model_name='endpointstatus',
            index=models.Index(fields=['hostname'], name='dashboard_e_hostnam_1da9d7_idx'),
        ),
    ]
