# Generated by Django 4.2.16 on 2026-09-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_endpointstatus_antivirus_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointstatus',
            name='agent_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='endpointstatus',
            name='hostname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='endpointstatus',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='endpointstatus',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
