# Generated by Django 4.2.16 on 2026-09-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_endpointstatus_agent_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointreport',
            name='mac_address',
            field=models.CharField(blank=True, db_index=True, max_length=17, null=True),
        ),
    ]
