# Generated by Django 4.2.16 on 2026-09-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_add_mac_to_endpoint_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointreport',
            name='cpu_model',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
