# Generated by Django 4.2.16 on 2026-09-08 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0010_endpointreport_cpu_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_employees', models.IntegerField(blank=True, null=True)),
                ('admin_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IndividualAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individual_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Individual Account',
                'verbose_name_plural': 'Individual Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('license_type', models.CharField(choices=[('commercial', 'Commercial'), ('trial', 'Trial'), ('education', 'Education'), ('nonprofit', 'Nonprofit')], default='commercial', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='active', max_length=20)),
                ('device_limit', models.IntegerField(help_text='Maximum number of devices that can be activated with this license')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='License expiration date')),
                ('valid_from', models.DateTimeField(default=django.db.models.functions.datetime.Now, help_text='When license becomes valid')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='dashboard.company')),
                ('individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='dashboard.individualaccount')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_licenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='dashboard.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='LicenseUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('activated', 'Device Activated'), ('deactivated', 'Device Deactivated'), ('validated', 'License Validated'), ('created', 'License Created'), ('renewed', 'License Renewed'), ('suspended', 'License Suspended'), ('error', 'Activation Error')], max_length=20)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('status_code', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='dashboard.license')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'License Usage Log',
                'verbose_name_plural': 'License Usage Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['license', 'timestamp'], name='dashboard_l_license_82c5b5_idx'), models.Index(fields=['action'], name='dashboard_l_action_d3eee0_idx'), models.Index(fields=['timestamp'], name='dashboard_l_timesta_293338_idx')],
            },
        ),
        migrations.CreateModel(
            name='LicenseDeviceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(db_index=True, max_length=17)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_devices', to=settings.AUTH_USER_MODEL)),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_records', to='dashboard.endpointstatus')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_records', to='dashboard.license')),
            ],
            options={
                'verbose_name': 'License Device Record',
                'verbose_name_plural': 'License Device Records',
                'ordering': ['-activated_at'],
                'indexes': [models.Index(fields=['license', 'mac_address'], name='dashboard_l_license_3e0ac2_idx'), models.Index(fields=['mac_address'], name='dashboard_l_mac_add_76a498_idx'), models.Index(fields=['activated_at'], name='dashboard_l_activat_7deb50_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='licensedevicerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('deactivated_at__isnull', True)), fields=('license', 'mac_address'), name='unique_active_mac_per_license'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['license_key'], name='dashboard_l_license_3a3018_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['company', 'status'], name='dashboard_l_company_5dd214_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['individual', 'status'], name='dashboard_l_individ_646f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['expires_at'], name='dashboard_l_expires_d73070_idx'),
        ),
        migrations.AddConstraint(
            model_name='license',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('company__isnull', False), ('individual__isnull', True)), models.Q(('company__isnull', True), ('individual__isnull', False)), _connector='OR'), name='license_has_owner'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'status'], name='dashboard_e_company_142cb5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('company', 'user')},
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['email'], name='dashboard_c_email_f33d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['status'], name='dashboard_c_status_dc6fd6_idx'),
        ),
    ]
