# Generated by Django 4.2.16 on 2026-09-09 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_company_individualaccount_license_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointstatus',
            name='hostname',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='endpointstatus',
            name='mac_address',
            field=models.CharField(blank=True, db_index=True, max_length=17, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='EndpointMetricsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('cpu_percent', models.FloatField(blank=True, null=True)),
                ('memory_percent', models.FloatField(blank=True, null=True)),
                ('disk_percent', models.FloatField(blank=True, null=True)),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('critical', 'Critical')], default='healthy', max_length=20)),
                ('health_score', models.FloatField(default=100.0)),
                ('firewall_active', models.BooleanField(blank=True, null=True)),
                ('antivirus_active', models.BooleanField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_history', to='dashboard.endpointstatus')),
            ],
            options={
                'verbose_name': 'Endpoint Metrics History',
                'verbose_name_plural': 'Endpoint Metrics Histories',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['endpoint', 'timestamp'], name='dashboard_e_endpoin_bc5f56_idx'), models.Index(fields=['timestamp'], name='dashboard_e_timesta_bbeb37_idx')],
            },
        ),
    ]
