# Generated by Django 4.2.16 on 2026-09-11 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_license_key_and_valid_from_in_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointreport',
            name='storage_provider',
            field=models.CharField(blank=True, default='local', max_length=20),
        ),
        migrations.CreateModel(
            name='EndpointDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(db_index=True, max_length=17, unique=True)),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('os', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endpoint_devices', to='dashboard.company')),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
        migrations.AddField(
            model_name='endpointcommand',
            name='endpoint_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commands_v2', to='dashboard.endpointdevice'),
        ),
        migrations.AddField(
            model_name='endpointmetricshistory',
            name='endpoint_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics_history_v2', to='dashboard.endpointdevice'),
        ),
        migrations.AddField(
            model_name='endpointreport',
            name='endpoint_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='dashboard.endpointdevice'),
        ),
        migrations.AddField(
            model_name='endpointstatus',
            name='endpoint_device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='dashboard.endpointdevice'),
        ),
        migrations.AddField(
            model_name='licensedevicerecord',
            name='endpoint_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_records', to='dashboard.endpointdevice'),
        ),
        migrations.AddField(
            model_name='licenseusagelog',
            name='endpoint_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_usage_logs', to='dashboard.endpointdevice'),
        ),
        migrations.AddField(
            model_name='poweractionlog',
            name='endpoint_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='power_logs_v2', to='dashboard.endpointdevice'),
        ),
        migrations.AddIndex(
            model_name='endpointdevice',
            index=models.Index(fields=['company', 'is_active'], name='dashboard_e_company_6ceb84_idx'),
        ),
        migrations.AddIndex(
            model_name='endpointdevice',
            index=models.Index(fields=['hostname'], name='dashboard_e_hostnam_0fb2c6_idx'),
        ),
    ]
