# Generated by Django 4.2.16 on 2026-09-11 09:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_endpointreport_storage_provider_endpointdevice_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE dashboard_endpointcommand DROP CONSTRAINT dashboard_endpointco_endpoint_device_id_25b0c5b2_fk_dashboard;
                    ALTER TABLE dashboard_endpointmetricshistory DROP CONSTRAINT dashboard_endpointme_endpoint_device_id_be3552c1_fk_dashboard;
                    ALTER TABLE dashboard_endpointreport DROP CONSTRAINT dashboard_endpointre_endpoint_device_id_ac56de40_fk_dashboard;
                    ALTER TABLE dashboard_endpointstatus DROP CONSTRAINT dashboard_endpointst_endpoint_device_id_7ef8339a_fk_dashboard;
                    ALTER TABLE dashboard_licensedevicerecord DROP CONSTRAINT dashboard_licensedev_endpoint_device_id_84295ab7_fk_dashboard;
                    ALTER TABLE dashboard_licenseusagelog DROP CONSTRAINT dashboard_licenseusa_endpoint_device_id_40391311_fk_dashboard;
                    ALTER TABLE dashboard_poweractionlog DROP CONSTRAINT dashboard_poweractio_endpoint_device_id_ceceb93c_fk_dashboard;
                    ALTER TABLE dashboard_endpointdevice ALTER COLUMN id DROP IDENTITY IF EXISTS;
                    ALTER TABLE dashboard_endpointdevice ALTER COLUMN id TYPE uuid USING gen_random_uuid();
                    ALTER TABLE dashboard_endpointcommand ALTER COLUMN endpoint_device_id TYPE uuid USING NULL::uuid;
                    ALTER TABLE dashboard_endpointmetricshistory ALTER COLUMN endpoint_device_id TYPE uuid USING NULL::uuid;
                    ALTER TABLE dashboard_endpointreport ALTER COLUMN endpoint_device_id TYPE uuid USING NULL::uuid;
                    ALTER TABLE dashboard_endpointstatus ALTER COLUMN endpoint_device_id TYPE uuid USING NULL::uuid;
                    ALTER TABLE dashboard_licensedevicerecord ALTER COLUMN endpoint_device_id TYPE uuid USING NULL::uuid;
                    ALTER TABLE dashboard_licenseusagelog ALTER COLUMN endpoint_device_id TYPE uuid USING NULL::uuid;
                    ALTER TABLE dashboard_poweractionlog ALTER COLUMN endpoint_device_id TYPE uuid USING NULL::uuid;
                    ALTER TABLE dashboard_endpointcommand ADD CONSTRAINT dashboard_endpointco_endpoint_device_id_25b0c5b2_fk_dashboard FOREIGN KEY (endpoint_device_id) REFERENCES dashboard_endpointdevice(id) DEFERRABLE INITIALLY DEFERRED;
                    ALTER TABLE dashboard_endpointmetricshistory ADD CONSTRAINT dashboard_endpointme_endpoint_device_id_be3552c1_fk_dashboard FOREIGN KEY (endpoint_device_id) REFERENCES dashboard_endpointdevice(id) DEFERRABLE INITIALLY DEFERRED;
                    ALTER TABLE dashboard_endpointreport ADD CONSTRAINT dashboard_endpointre_endpoint_device_id_ac56de40_fk_dashboard FOREIGN KEY (endpoint_device_id) REFERENCES dashboard_endpointdevice(id) DEFERRABLE INITIALLY DEFERRED;
                    ALTER TABLE dashboard_endpointstatus ADD CONSTRAINT dashboard_endpointst_endpoint_device_id_7ef8339a_fk_dashboard FOREIGN KEY (endpoint_device_id) REFERENCES dashboard_endpointdevice(id) DEFERRABLE INITIALLY DEFERRED;
                    ALTER TABLE dashboard_licensedevicerecord ADD CONSTRAINT dashboard_licensedev_endpoint_device_id_84295ab7_fk_dashboard FOREIGN KEY (endpoint_device_id) REFERENCES dashboard_endpointdevice(id) DEFERRABLE INITIALLY DEFERRED;
                    ALTER TABLE dashboard_licenseusagelog ADD CONSTRAINT dashboard_licenseusa_endpoint_device_id_40391311_fk_dashboard FOREIGN KEY (endpoint_device_id) REFERENCES dashboard_endpointdevice(id) DEFERRABLE INITIALLY DEFERRED;
                    ALTER TABLE dashboard_poweractionlog ADD CONSTRAINT dashboard_poweractio_endpoint_device_id_ceceb93c_fk_dashboard FOREIGN KEY (endpoint_device_id) REFERENCES dashboard_endpointdevice(id) DEFERRABLE INITIALLY DEFERRED;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='endpointdevice',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
