# Generated by Django 5.0 on 2026-09-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0018_endpointstatus_connection_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="endpointstatus",
            name="uptime_seconds",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="endpointmetricshistory",
            name="uptime_seconds",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]