"""
macOS HTML audit report parser.

Supports reports generated by the macOS audit script (Mac-Security-Audit-Report-* format).
Returns a dict with keys matching EndpointReport model fields.

Changes vs old format:
 - IP Address now present in the System Information table (row "IP Address")
 - Antivirus/EDR section present — detect "No third-party" vs installed product
 - Screen lock fields parsed from scorecard and Screen Lock section
 - USB detection via USB Devices section
 - AnyDesk / TeamViewer detection from Installed Applications + Startup Items
 - Pending updates via Software Update Status section (count "* Label:" entries)
 - launchd non-zero exit services tracked in raw_data
 - World-writable dirs tracked in raw_data
"""
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from bs4 import BeautifulSoup

from .base import clean, extract_int, safe_dt


# ── helpers ──────────────────────────────────────────────────────────────────

def _label_value(soup: BeautifulSoup, label: str) -> Optional[str]:
    """Find a table row whose first cell equals *label* and return the second cell."""
    for row in soup.find_all("tr"):
        cells = [clean(td.get_text()) for td in row.find_all(["td", "th"])]
        if len(cells) >= 2 and label.lower() == cells[0].lower():
            return cells[1]
    return None


def _section_text(soup: BeautifulSoup, heading_text: str) -> str:
    """Return combined text under the section that starts with *heading_text*."""
    heading = soup.find(
        lambda t: t.name in ("h1", "h2", "h3", "h4")
        and heading_text.lower() in t.get_text(strip=True).lower(),
    )
    if not heading:
        return ""
    parts = []
    for sib in heading.find_next_siblings():
        if sib.name in ("h1", "h2", "h3", "h4"):
            break
        parts.append(clean(sib.get_text()))
    return " ".join(parts)


def _scorecard(soup: BeautifulSoup, check_label: str) -> tuple[str, str]:
    """
    Return (result, detail) from the Security Scorecard for *check_label*.
    result is 'pass', 'fail', 'warn', 'info', or ''. Both lowercased.
    """
    sc_heading = soup.find(
        lambda t: t.name in ("h1", "h2", "h3", "h4")
        and "security scorecard" in t.get_text(strip=True).lower(),
    )
    if not sc_heading:
        return "", ""
    sc_tbl = sc_heading.find_next("table")
    if not sc_tbl:
        return "", ""
    for row in sc_tbl.find_all("tr"):
        cells = [clean(td.get_text()) for td in row.find_all(["td", "th"])]
        if len(cells) >= 3 and check_label.lower() in cells[0].lower():
            return cells[1].lower().strip(), cells[2].lower().strip()
    return "", ""


def _find_section_table(soup: BeautifulSoup, keyword: str):
    """Return the <table> following the first heading that contains *keyword*."""
    h = soup.find(
        lambda t: t.name in ("h1", "h2", "h3", "h4")
        and keyword.lower() in t.get_text(strip=True).lower(),
    )
    return h.find_next("table") if h else None


def _table_rows(table) -> list[list[str]]:
    rows = []
    for tr in table.find_all("tr"):
        cols = [clean(td.get_text()) for td in tr.find_all(["td", "th"])]
        if any(c for c in cols):
            rows.append(cols)
    return rows


# ── main parser ──────────────────────────────────────────────────────────────

def parse(filepath: str | Path) -> dict:
    """
    Parse a macOS HTML audit report and return a normalised dict.
    Raises ValueError if the file doesn't look like a macOS report.
    """
    filepath = Path(filepath)
    html = filepath.read_text(errors="replace")
    soup = BeautifulSoup(html, "lxml")

    page_text = soup.get_text()
    if "macos" not in page_text.lower() and "mac os" not in page_text.lower() \
            and "darwin" not in page_text.lower():
        raise ValueError(f"{filepath.name} does not appear to be a macOS report")

    # ── Report date ───────────────────────────────────────────────────────
    # Filename: Mac-Security-Audit-Report-20260803-130642.html
    report_date = None
    fname_match = re.search(r"(\d{8})-(\d{6})", filepath.stem)
    if fname_match:
        dt_str = fname_match.group(1) + fname_match.group(2)
        report_date = safe_dt(dt_str, "%Y%m%d%H%M%S")
    if not report_date:
        # "Generated: Mon Aug  3 13:10:57 IST 2026"
        gen_match = re.search(
            r"Generated[:\s]+(\w{3}\s+\w{3}\s+\d+\s+[\d:]+\s*\w+\s+\d{4})",
            page_text, re.IGNORECASE,
        )
        if gen_match:
            raw_dt = gen_match.group(1).strip()
            for fmt in ("%a %b %d %H:%M:%S %Z %Y", "%a %b  %d %H:%M:%S %Z %Y"):
                dt = safe_dt(raw_dt, fmt)
                if dt:
                    report_date = dt
                    break
    if not report_date:
        report_date = datetime.fromtimestamp(filepath.stat().st_mtime, tz=timezone.utc)

    # ── System Information ────────────────────────────────────────────────
    hostname   = _label_value(soup, "Hostname") or _label_value(soup, "Host") or filepath.stem
    os_name    = _label_value(soup, "OS") or ""
    cpu        = _label_value(soup, "CPU") or ""
    ram        = _label_value(soup, "Memory") or ""
    # IP address — now present in the new System Information table
    ip_address = _label_value(soup, "IP Address") or ""

    # Architecture from CPU string
    architecture = "x86_64"
    cpu_lower = cpu.lower()
    if any(kw in cpu_lower for kw in ("m1", "m2", "m3", "m4", "apple silicon", "apple m")):
        architecture = "arm64"

    # OS version
    os_version = os_name   # e.g. "Mac OS X 10.15.7 (19H15)"

    # ── FileVault (encryption) ─────────────────────────────────────────────
    encryption_enabled = None
    sc_result, sc_fv = _scorecard(soup, "Disk Encryption")
    if sc_result:
        encryption_enabled = sc_result == "pass"
    else:
        fv_text = _section_text(soup, "Disk Encryption") or _section_text(soup, "FileVault")
        if not fv_text:
            fv_match = re.search(r"FileVault[:\s]*(.*?)(?:\n|Firewall|XProtect|$)", page_text, re.IGNORECASE)
            fv_text = fv_match.group(1)[:120] if fv_match else ""
        if fv_text:
            encryption_enabled = "off" not in fv_text.lower() and "disabled" not in fv_text.lower()

    # ── Firewall ──────────────────────────────────────────────────────────
    firewall_enabled = None
    sc_result, sc_fw = _scorecard(soup, "Firewall")
    if sc_result:
        if sc_result == "pass" or "state = 1" in sc_fw or "enabled" in sc_fw:
            firewall_enabled = True
        else:
            firewall_enabled = False
    else:
        fw_match = re.search(r"Firewall[:\s]+.*?State\s*=\s*(\d)", page_text, re.IGNORECASE | re.DOTALL)
        if fw_match:
            firewall_enabled = fw_match.group(1) == "1"

    # ── Gatekeeper ────────────────────────────────────────────────────────
    gatekeeper_enabled = None
    sc_result, sc_gk = _scorecard(soup, "Gatekeeper")
    if sc_result:
        gatekeeper_enabled = sc_result == "pass"
    else:
        gk_match = re.search(r"Gatekeeper[:\s]*(.*?)(?:\n|SIP|$)", page_text, re.IGNORECASE)
        if gk_match:
            gatekeeper_enabled = "disabled" not in gk_match.group(1)[:80].lower()

    # ── SIP ───────────────────────────────────────────────────────────────
    sip_enabled = None
    sc_result, sc_sip = _scorecard(soup, "System Integrity Protection")
    if sc_result:
        sip_enabled = sc_result == "pass"
    else:
        sip_match = re.search(
            r"System Integrity Protection status[:\s]*(enabled|disabled)", page_text, re.IGNORECASE
        )
        if sip_match:
            sip_enabled = sip_match.group(1).lower() == "enabled"

    # ── Antivirus / EDR ───────────────────────────────────────────────────
    antivirus_installed = None
    sc_result, sc_av = _scorecard(soup, "Antivirus")
    if sc_result:
        if "no third-party" in sc_av or "not detected" in sc_av:
            antivirus_installed = False
        elif sc_result == "pass":
            antivirus_installed = True
        else:
            antivirus_installed = False
    else:
        av_match = re.search(
            r"Antivirus[/\s\w]*?EDR[:\s]*(.*?)(?:\n|Firewall|$)", page_text, re.IGNORECASE
        )
        if av_match:
            av_text = av_match.group(1)[:120]
            antivirus_installed = (
                "no third-party" not in av_text.lower()
                and "not detected" not in av_text.lower()
            )

    # ── Pending updates ───────────────────────────────────────────────────
    pending_updates = None
    sc_result, sc_upd = _scorecard(soup, "Pending macOS Updates")
    if sc_result:
        if sc_result == "pass" or "up to date" in sc_upd:
            pending_updates = 0
        else:
            m = re.search(r"(\d+)", sc_upd)
            pending_updates = int(m.group(1)) if m else None
    if pending_updates is None:
        sw_upd_text = _section_text(soup, "Software Update")
        if sw_upd_text:
            labels = re.findall(r"\*\s+Label:", sw_upd_text, re.IGNORECASE)
            if labels:
                pending_updates = len(labels)

    # ── Screen lock ───────────────────────────────────────────────────────
    screen_lock_enabled = None
    sc_result, sc_sl = _scorecard(soup, "Screen Lock")
    if sc_result:
        screen_lock_enabled = sc_result == "pass"

    # ── Secure Boot / TPM ─────────────────────────────────────────────────
    secure_boot_enabled = None
    tpm_present         = None
    sc_result, sc_sb = _scorecard(soup, "Secure Boot")
    if sc_result:
        if "no t2 chip" in sc_sb or "not available" in sc_sb or sc_result == "info":
            secure_boot_enabled = False
            tpm_present = False
        elif sc_result == "pass":
            secure_boot_enabled = True
    else:
        sb_text = _section_text(soup, "Secure Boot")
        if "no t2 chip" in sb_text.lower() or "not available" in sb_text.lower():
            secure_boot_enabled = False
            tpm_present = False
        elif "full security" in sb_text.lower() or "enabled" in sb_text.lower():
            secure_boot_enabled = True

    # ── SSH ───────────────────────────────────────────────────────────────
    ssh_enabled = None
    sc_result, sc_ssh = _scorecard(soup, "SSH")
    if sc_result:
        ssh_enabled = sc_result != "pass" and "off" not in sc_ssh and "not active" not in sc_ssh
        if "off" in sc_ssh or "not active" in sc_ssh:
            ssh_enabled = False
        elif sc_result == "pass":
            ssh_enabled = False  # SSH pass = Remote Login Off = safe
    else:
        ssh_match = re.search(r"Remote Login[:\s]*(Remote Login:\s*)?(On|Off)", page_text, re.IGNORECASE)
        if ssh_match:
            ssh_enabled = "on" in ssh_match.group(0).lower().split("login")[-1]

    # ── Remote access detection ───────────────────────────────────────────
    anydesk_running       = False
    teamviewer_running    = False
    chrome_remote_desktop = False

    # Check installed applications section
    apps_text = _section_text(soup, "Installed Applications")
    # Check startup items
    startup_text = _section_text(soup, "Startup Items") + _section_text(soup, "Login Items")
    # Combined check
    combined = (apps_text + startup_text + page_text).lower()

    if "anydesk" in combined:
        anydesk_running = True
    if "teamviewer" in combined:
        teamviewer_running = True
    if "chrome remote desktop" in combined:
        chrome_remote_desktop = True

    # RDP check (port 3389)
    rdp_open = "3389" in page_text

    # ── USB storage ───────────────────────────────────────────────────────
    usb_storage_enabled = None
    usb_section = _section_text(soup, "USB Devices")
    if usb_section:
        # If there are non-HID USB devices (storage), flag as potentially enabled
        # macOS doesn't have a direct "USB storage disabled" setting like Windows
        usb_storage_enabled = None   # informational only on macOS

    # ── Passwordless sudo / admin ─────────────────────────────────────────
    passwordless_sudo = False
    pls_text = _section_text(soup, "Passwordless Sudo")
    if pls_text:
        passwordless_sudo = (
            "no passwordless" not in pls_text.lower()
            and "none found" not in pls_text.lower()
        )

    # ── Password policy ───────────────────────────────────────────────────
    pass_min_len = None
    pw_text = _section_text(soup, "Password Policy")
    if pw_text:
        # "policyAttributePassword matches '^$|.{4,}+'"  → min length 4
        len_m = re.search(r"\{(\d+),", pw_text)
        if len_m:
            pass_min_len = int(len_m.group(1))

    # ── Listening ports ───────────────────────────────────────────────────
    listeners = []
    net_heading = soup.find(
        lambda t: t.name in ("h2", "h3") and "listening" in t.get_text(strip=True).lower()
    )
    if net_heading:
        pre_or_table = net_heading.find_next(["pre", "table"])
        if pre_or_table:
            for row in pre_or_table.find_all("tr"):
                cols = [clean(td.get_text()) for td in row.find_all(["td", "th"])]
                if cols and cols[0] not in ("COMMAND", ""):
                    listeners.append(" ".join(cols))

    # ── Applications list ─────────────────────────────────────────────────
    apps = []
    app_heading = soup.find(
        lambda t: t.name in ("h2", "h3", "h4")
        and "installed applications" in t.get_text(strip=True).lower(),
    )
    if app_heading:
        for sib in app_heading.find_next_siblings():
            if sib.name in ("h2", "h3", "h4"):
                break
            text = sib.get_text()
            for line in text.splitlines():
                line = line.strip()
                if line and ".app" in line.lower():
                    apps.append(line)

    # ── Admin users ───────────────────────────────────────────────────────
    admin_users = []
    _, sc_admin = _scorecard(soup, "Local Admin")
    if sc_admin:
        m = re.search(r":\s*(.+)$", sc_admin)
        if m:
            admin_users = m.group(1).strip().split()
    if not admin_users:
        admin_text = _section_text(soup, "Admin Group")
        if admin_text:
            m = re.search(r"GroupMembership[:\s]+(.+)", admin_text)
            if m:
                admin_users = m.group(1).strip().split()

    # ── launchd non-zero services ─────────────────────────────────────────
    launchd_errors = []
    lj_heading = soup.find(
        lambda t: t.name in ("h2", "h3", "h4")
        and "non-zero" in t.get_text(strip=True).lower(),
    )
    if lj_heading:
        tbl = lj_heading.find_next("table")
        if tbl:
            for row in _table_rows(tbl):
                if row and row[0] not in ("PID", ""):
                    launchd_errors.append({
                        "pid":    row[0],
                        "status": row[1] if len(row) > 1 else "",
                        "label":  row[2] if len(row) > 2 else "",
                    })

    raw_data = {
        "hostname":              hostname,
        "os":                    os_name,
        "cpu":                   cpu,
        "ram":                   ram,
        "ip":                    ip_address,
        "filevault":             str(encryption_enabled),
        "firewall":              str(firewall_enabled),
        "gatekeeper":            str(gatekeeper_enabled),
        "sip":                   str(sip_enabled),
        "antivirus":             str(antivirus_installed),
        "pending_updates":       str(pending_updates),
        "screen_lock_enabled":   str(screen_lock_enabled),
        "secure_boot":           str(secure_boot_enabled),
        "ssh":                   str(ssh_enabled),
        "passwordless_sudo":     str(passwordless_sudo),
        "anydesk":               str(anydesk_running),
        "teamviewer":            str(teamviewer_running),
        "chrome_remote_desktop": str(chrome_remote_desktop),
        "rdp":                   str(rdp_open),
        "network_listeners":     listeners,
        "applications":          apps,
        "admin_users":           admin_users,
        "launchd_errors":        launchd_errors,
    }

    return {
        # Identity
        "hostname":              hostname,
        "os_type":               "macos",
        "os_name":               os_name,
        "os_version":            os_version,
        "architecture":          architecture,
        "ip_address":            ip_address,
        "report_date":           report_date,
        "report_file":           str(filepath),
        # Hardware
        "cpu":                   cpu,
        "ram":                   ram,
        # Security
        "firewall_enabled":      firewall_enabled,
        "encryption_enabled":    encryption_enabled,
        "antivirus_installed":   antivirus_installed,
        "antivirus_name":        "",
        "antivirus_realtime":    None,
        "antivirus_updated_at":  None,
        "antivirus_tamper":      None,
        "secure_boot_enabled":   secure_boot_enabled,
        "tpm_present":           tpm_present,
        "ssh_enabled":           ssh_enabled,
        "auditd_enabled":        None,
        "passwordless_sudo":     passwordless_sudo,
        "sip_enabled":           sip_enabled,
        "gatekeeper_enabled":    gatekeeper_enabled,
        # New fields
        "usb_storage_enabled":   usb_storage_enabled,
        "screen_lock_enabled":   screen_lock_enabled,
        "chrome_remote_desktop": chrome_remote_desktop,
        # Updates
        "pending_updates":       pending_updates,
        "last_patch_date":       None,
        # Password policy
        "pass_max_days":         None,
        "pass_min_days":         None,
        "pass_min_len":          pass_min_len,
        "lockout_threshold":     None,
        # Remote access
        "anydesk_running":       anydesk_running,
        "teamviewer_running":    teamviewer_running,
        "rdp_open":              rdp_open,
        # Raw snapshot
        "raw_data":              raw_data,
    }
