"""
Windows HTML audit report parser.

Supports reports generated by the Windows audit script
(System-Audit-Report-YYYYMMDD-HHMMSS format).
Returns a dict with keys matching EndpointReport model fields.

New format changes handled:
 - System Info table now has 14 columns (added Domain/Workgroup, OS Install Date, Uptime)
 - AV table now has 10 columns (Antispyware, Behavior Monitor, Cloud Protection,
   Tamper Protection, Signature Version, Signature Last Updated, Last Quick Scan, Last Full Scan)
 - Patch Management split into Section 6 (Installed) and 6a (Pending Updates)
 - Pending count comes from "Pending Windows Updates" scorecard or dedicated pending table
 - Date format in AV/patch rows: M/d/yyyy h:mm:ss tt  (e.g. 8/3/2026 4:53:36 AM)
 - USB Storage section present
 - Screen Lock section present
 - Chrome Remote Desktop detected via services/installed software
"""
import re
from datetime import datetime, timezone, date
from pathlib import Path
from typing import Optional

from bs4 import BeautifulSoup

from .base import clean, extract_int, safe_dt


# ── helpers ──────────────────────────────────────────────────────────────────

def _table_rows(table) -> list[list[str]]:
    """Return all rows of a table as a list of string lists."""
    rows = []
    for tr in table.find_all("tr"):
        cols = [clean(td.get_text()) for td in tr.find_all(["td", "th"])]
        if any(c for c in cols):
            rows.append(cols)
    return rows


def _first_value_row(table, header_skip: int = 1) -> Optional[list[str]]:
    """Return the first non-header row of a table."""
    rows = _table_rows(table)
    if len(rows) > header_skip:
        return rows[header_skip]
    return None


def _find_section(soup: BeautifulSoup, keyword: str):
    """Return the <table> that follows the first heading containing *keyword*."""
    h = soup.find(
        lambda t: t.name in ("h1", "h2", "h3", "h4")
        and keyword.lower() in t.get_text(strip=True).lower(),
    )
    return h.find_next("table") if h else None


def _parse_win_dt(dt_str: str) -> Optional[datetime]:
    """
    Parse Windows datetime strings.  The new reports use:
      M/d/yyyy h:mm:ss tt  → e.g. "8/3/2026 4:53:36 AM"  or "07/29/2026 00:00:00"
    Old format was dd-MM-yyyy HH:mm:ss – keep as fallback.
    """
    for fmt in (
        "%m/%d/%Y %I:%M:%S %p",   # 8/3/2026 4:53:36 AM
        "%m/%d/%Y %H:%M:%S",      # 07/29/2026 00:00:00
        "%d-%m-%Y %H:%M:%S",      # legacy
    ):
        dt = safe_dt(dt_str.strip(), fmt)
        if dt:
            return dt
    return None


def _parse_win_date(dt_str: str) -> Optional[date]:
    """Parse a date from a Windows datetime string."""
    dt = _parse_win_dt(dt_str)
    return dt.date() if dt else None


def _scorecard(soup: BeautifulSoup, check_label: str) -> tuple[str, str]:
    """
    Return (result, detail) from the Security Scorecard for *check_label*.
    result is 'pass', 'fail', 'warn', 'info', or ''. Both lowercased.
    """
    sc_tbl = _find_section(soup, "Security Scorecard")
    if not sc_tbl:
        return "", ""
    for row in _table_rows(sc_tbl):
        if len(row) >= 3 and check_label.lower() in row[0].lower():
            return row[1].lower().strip(), row[2].lower().strip()
    return "", ""


# ── main parser ──────────────────────────────────────────────────────────────

def parse(filepath: str | Path) -> dict:
    """
    Parse a Windows HTML audit report and return a normalised dict.
    Raises ValueError if the file doesn't look like a Windows report.
    """
    filepath = Path(filepath)
    html = filepath.read_text(errors="replace")
    soup = BeautifulSoup(html, "lxml")

    page_text = soup.get_text()
    if "windows" not in page_text.lower() and "microsoft" not in page_text.lower():
        raise ValueError(f"{filepath.name} does not appear to be a Windows report")

    # ── Report date ───────────────────────────────────────────────────────
    report_date = None
    fname_match = re.search(r"(\d{8})-(\d{6})", filepath.stem)
    if fname_match:
        dt_str = fname_match.group(1) + fname_match.group(2)
        report_date = safe_dt(dt_str, "%Y%m%d%H%M%S")
    if not report_date:
        gen_match = re.search(
            r"Generated[:\s]+(\d{1,2}/\d{1,2}/\d{4}\s+\d{1,2}:\d{2}:\d{2}(?:\s*(?:AM|PM))?)",
            page_text, re.IGNORECASE,
        )
        if gen_match:
            report_date = _parse_win_dt(gen_match.group(1))
    if not report_date:
        report_date = datetime.fromtimestamp(filepath.stat().st_mtime, tz=timezone.utc)

    # ── 1. System Information ─────────────────────────────────────────────
    # New column layout (14 cols):
    #   0: Computer Name  1: Domain/Workgroup  2: Manufacturer  3: Model
    #   4: Serial Number  5: OS  6: OS Version  7: Build Number
    #   8: OS Install Date  9: Processor  10: RAM  11: BIOS  12: Last Boot  13: Uptime
    # Old layout (10+ cols):
    #   0: Computer Name  1: Manufacturer  2: Model  3: OS  4: OS Version
    #   5: Build  6: Processor  7: RAM  8: BIOS  9: Last Boot
    sys_tbl = _find_section(soup, "System Information")
    sys_info = {}
    if sys_tbl:
        row = _first_value_row(sys_tbl)
        if row:
            ncols = len(row)
            if ncols >= 12:
                # New 14-column format
                sys_info = {
                    "hostname":     row[0],
                    "domain":       row[1],
                    "manufacturer": row[2],
                    "model":        row[3],
                    "serial":       row[4],
                    "os_name":      row[5],
                    "os_version":   row[6],
                    "build":        row[7],
                    "os_install":   row[8],
                    "cpu":          row[9],
                    "ram":          row[10],
                    "bios":         row[11],
                    "last_boot":    row[12] if ncols > 12 else "",
                    "uptime":       row[13] if ncols > 13 else "",
                }
            elif ncols >= 8:
                # Old 10-column format
                sys_info = {
                    "hostname":     row[0],
                    "manufacturer": row[1],
                    "model":        row[2],
                    "os_name":      row[3],
                    "os_version":   row[4],
                    "build":        row[5],
                    "cpu":          row[6],
                    "ram":          row[7],
                    "bios":         row[8] if ncols > 8 else "",
                    "last_boot":    row[9] if ncols > 9 else "",
                }

    hostname   = sys_info.get("hostname", filepath.stem)
    os_name    = sys_info.get("os_name", "")
    os_version = (sys_info.get("os_version", "") + " " + sys_info.get("build", "")).strip()
    cpu        = sys_info.get("cpu", "")
    ram        = sys_info.get("ram", "")
    bios       = sys_info.get("bios", "")

    # ── IP address (from Network Adapters section) ─────────────────────
    ip_address = ""
    net_tbl = _find_section(soup, "Network Adapters")
    if net_tbl:
        for row in _table_rows(net_tbl):
            if len(row) >= 2:
                ip_m = re.search(r"(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})", row[1])
                if ip_m:
                    cand = ip_m.group(1)
                    if not cand.startswith("127.") and not cand.startswith("0."):
                        ip_address = cand
                        break
    if not ip_address:
        # Fallback: first non-loopback IP anywhere in page
        for m in re.finditer(r"(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})", page_text):
            cand = m.group(1)
            if not cand.startswith("127.") and not cand.startswith("0."):
                ip_address = cand
                break

    # ── Antivirus / EDR (Section 5) ───────────────────────────────────────
    # New columns (0-indexed):
    #   0: Antivirus Enabled   1: Real Time Protection   2: Antispyware Enabled
    #   3: Behavior Monitor    4: Cloud Protection       5: Tamper Protection
    #   6: Signature Version   7: Signature Last Updated 8: Last Quick Scan  9: Last Full Scan
    # Old columns:
    #   0: Antivirus Enabled   1: Real Time Protection   ...  4: Last Updated
    av_tbl = _find_section(soup, "Antivirus")
    antivirus_installed      = None
    antivirus_realtime       = None
    antivirus_updated_at     = None
    antivirus_tamper         = None
    if av_tbl:
        av_row = _first_value_row(av_tbl)
        if av_row:
            antivirus_installed  = av_row[0].lower() == "true" if len(av_row) > 0 else None
            antivirus_realtime   = av_row[1].lower() == "true" if len(av_row) > 1 else None
            if len(av_row) > 5:
                # New format: tamper protection at index 5
                antivirus_tamper = av_row[5].lower() == "true"
                # Signature Last Updated at index 7
                if len(av_row) > 7 and av_row[7]:
                    antivirus_updated_at = _parse_win_dt(av_row[7])
            elif len(av_row) > 4 and av_row[4]:
                # Old format: last updated at index 4
                antivirus_updated_at = _parse_win_dt(av_row[4])

    # ── Patch Management — Installed (Section 6) ──────────────────────────
    # New: Columns are HotFixID | Description | InstalledOn
    # Dates now in format "M/d/yyyy HH:MM:SS" e.g. "7/29/2026 12:00:00 AM"
    patch_installed_tbl = _find_section(soup, "Patch Management")
    last_patch_date = None
    installed_patches = []
    if patch_installed_tbl:
        for row in _table_rows(patch_installed_tbl):
            if row and row[0] not in ("HotFixID", "Title", ""):
                installed_patches.append({
                    "id":          row[0],
                    "description": row[1] if len(row) > 1 else "",
                    "installed_on": row[2] if len(row) > 2 else "",
                })
                if len(row) > 2 and row[2]:
                    pd = _parse_win_date(row[2])
                    if pd and (last_patch_date is None or pd > last_patch_date):
                        last_patch_date = pd

    # ── Patch Management — Pending Updates (Section 6a) ──────────────────
    # First try scorecard "Pending Windows Updates" result+detail
    # Detail may be "9 update(s) pending" or just "update(s) pending" (count missing)
    pending_updates = None
    sc_result, sc_upd = _scorecard(soup, "Pending Windows Updates")
    if sc_result:
        if sc_result == "pass":
            pending_updates = 0
        else:
            m = re.search(r"(\d+)", sc_upd)
            pending_updates = int(m.group(1)) if m else None
    if pending_updates is None:
        # Fall back to counting rows in the dedicated pending table
        pending_tbl = None
        for h in soup.find_all(["h2", "h3", "h4"]):
            ht = clean(h.get_text()).lower()
            if "pending" in ht and ("update" in ht or "patch" in ht):
                pending_tbl = h.find_next("table")
                break
        if pending_tbl:
            p_rows = [r for r in _table_rows(pending_tbl)
                      if r and r[0] not in ("Title", "HotFixID", "")]
            pending_updates = len(p_rows)
    if pending_updates is None:
        upd_m = re.search(r"(\d+)\s+update[s]?\s+pending", page_text, re.IGNORECASE)
        if upd_m:
            pending_updates = int(upd_m.group(1))

    # ── Firewall (Section 8) ──────────────────────────────────────────────
    fw_tbl = _find_section(soup, "Firewall")
    firewall_enabled = None
    if fw_tbl:
        fw_data = [
            r for r in _table_rows(fw_tbl)
            if r and r[0] not in ("Name", "")
        ]
        if fw_data:
            firewall_enabled = all(
                r[1].lower() == "true" for r in fw_data if len(r) > 1
            )

    # ── Secure Boot (Section 9) ───────────────────────────────────────────
    sb_tbl = _find_section(soup, "Secure Boot")
    secure_boot_enabled = None
    if sb_tbl:
        sb_row = _first_value_row(sb_tbl)
        if sb_row:
            val = sb_row[0].lower()
            if "true" in val:
                secure_boot_enabled = True
            elif "false" in val or "n/a" in val or "legacy" in val:
                secure_boot_enabled = False

    # ── TPM (Section 10) ──────────────────────────────────────────────────
    tpm_tbl = _find_section(soup, "TPM")
    tpm_present = None
    if tpm_tbl:
        tpm_row = _first_value_row(tpm_tbl)
        if tpm_row:
            # TPM Present column (first col)
            tpm_present = tpm_row[0].lower() == "true"

    # ── Password Policy (Section 11) ─────────────────────────────────────
    # The policy is in a single-row table; column headers are the policy names.
    pass_max_days     = None
    pass_min_days     = None
    pass_min_len      = None
    lockout_threshold = None
    pw_tbl = _find_section(soup, "Password Policy")
    if pw_tbl:
        rows = _table_rows(pw_tbl)
        if len(rows) >= 2:
            headers = [h.lower() for h in rows[0]]
            vals    = rows[1]
            for i, h in enumerate(headers):
                if i >= len(vals):
                    break
                v = vals[i]
                if "maximum password age" in h:
                    pass_max_days = extract_int(v)
                elif "minimum password age" in h:
                    pass_min_days = extract_int(v)
                elif "minimum password length" in h:
                    pass_min_len = extract_int(v)
                elif "lockout threshold" in h:
                    lockout_threshold = extract_int(v)
    # Plain-text fallback
    if pass_max_days is None:
        pw_section = re.search(
            r"Password Policy.*?(?=\d+\.|$)", page_text, re.IGNORECASE | re.DOTALL
        )
        if pw_section:
            pw_text = pw_section.group(0)
            max_m = re.search(r"Maximum password age.*?(\d+)", pw_text)
            min_m = re.search(r"Minimum password age.*?(\d+)", pw_text)
            len_m = re.search(r"Minimum password length.*?(\d+)", pw_text)
            lok_m = re.search(r"Lockout threshold.*?(\d+)", pw_text)
            pass_max_days     = int(max_m.group(1)) if max_m and pass_max_days is None else pass_max_days
            pass_min_days     = int(min_m.group(1)) if min_m and pass_min_days is None else pass_min_days
            pass_min_len      = int(len_m.group(1)) if len_m and pass_min_len  is None else pass_min_len
            lockout_threshold = int(lok_m.group(1)) if lok_m and lockout_threshold is None else lockout_threshold

    # ── Screen Lock (Section 12) ──────────────────────────────────────────
    screen_lock_enabled = None
    sl_tbl = _find_section(soup, "Screen Lock")
    if sl_tbl:
        sl_row = _first_value_row(sl_tbl)
        if sl_row:
            # Screen Saver Active (User) is col 0 — "1" means active
            val = sl_row[0].strip()
            if val == "1":
                screen_lock_enabled = True
            elif val == "0":
                screen_lock_enabled = False
    if screen_lock_enabled is None:
        sc_result, sc_sl = _scorecard(soup, "Screen Lock")
        if sc_result:
            screen_lock_enabled = sc_result == "pass"

    # ── USB Storage (Section 3) ───────────────────────────────────────────
    usb_storage_enabled = None
    sc_result, sc_usb = _scorecard(soup, "USB Storage")
    if sc_result:
        usb_storage_enabled = sc_result != "pass"  # Warn/Fail = enabled (unrestricted)
    else:
        usb_tbl = _find_section(soup, "USB Storage")
        if usb_tbl:
            usb_row = _first_value_row(usb_tbl)
            if usb_row:
                usb_storage_enabled = "enabled" in usb_row[0].lower()

    # ── BitLocker / Encryption ────────────────────────────────────────────
    encryption_enabled = None
    sc_result, sc_enc = _scorecard(soup, "BitLocker")
    if sc_result:
        if sc_result == "pass" or re.search(r"\bon\b|protected|enabled", sc_enc):
            encryption_enabled = True
        else:
            # Fail: "off / 0% encrypted", "unavailable", "home edition"
            encryption_enabled = False
    if encryption_enabled is None:
        enc_section = re.search(r"BitLocker(.*?)(?:\d+\.|$)", page_text, re.IGNORECASE | re.DOTALL)
        if enc_section:
            enc_text = enc_section.group(1)[:300]
            if re.search(r"Protection\s*(On|Enabled)", enc_text, re.IGNORECASE):
                encryption_enabled = True
            elif re.search(r"(Protection\s*(Off|Disabled|Not)|Unavailable|No data|0%)", enc_text, re.IGNORECASE):
                encryption_enabled = False

    # ── Running Services (Section 19) ─────────────────────────────────────
    svc_tbl = _find_section(soup, "Running Services")
    services = []
    if svc_tbl:
        for row in _table_rows(svc_tbl):
            if row and row[0] not in ("Name", ""):
                services.append({
                    "name":    row[0],
                    "display": row[1] if len(row) > 1 else "",
                    "status":  row[2] if len(row) > 2 else "",
                })

    # ── Open Listening Ports (Section 20) ─────────────────────────────────
    port_tbl = _find_section(soup, "Open Listening Ports")
    open_ports         = []
    rdp_open           = False
    anydesk_running    = False
    teamviewer_running = False
    chrome_remote_desktop = False
    if port_tbl:
        for row in _table_rows(port_tbl):
            if row and row[0] not in ("LocalAddress", ""):
                port    = row[1] if len(row) > 1 else ""
                process = row[3] if len(row) > 3 else ""
                open_ports.append({"address": row[0], "port": port, "process": process})
                if port == "3389":
                    rdp_open = True
                if port == "7070":
                    anydesk_running = True

    # Detect remote tools from services list
    svc_names_lower = " ".join(s.get("name", "") + " " + s.get("display", "") for s in services).lower()
    if "anydesk" in svc_names_lower:
        anydesk_running = True
    if "teamviewer" in svc_names_lower:
        teamviewer_running = True
    if "chromoting" in svc_names_lower or "chrome remote desktop" in svc_names_lower:
        chrome_remote_desktop = True

    # ── Installed Software (Section 23) ───────────────────────────────────
    sw_tbl = _find_section(soup, "Installed Software")
    if sw_tbl is None:
        sw_tbl = _find_section(soup, "Installed Software Inventory")
    installed_sw = []
    if sw_tbl:
        for row in _table_rows(sw_tbl):
            if row and row[0] not in ("DisplayName", ""):
                name = row[0]
                installed_sw.append({
                    "name":      name,
                    "version":   row[1] if len(row) > 1 else "",
                    "publisher": row[2] if len(row) > 2 else "",
                })
                lname = name.lower()
                if "anydesk" in lname:
                    anydesk_running = True
                if "teamviewer" in lname:
                    teamviewer_running = True
                if "chrome remote desktop" in lname:
                    chrome_remote_desktop = True

    # Also check page text for chrome remote desktop
    if "chrome remote desktop" in page_text.lower():
        chrome_remote_desktop = True

    # ── Browser Extensions (Section 24) ───────────────────────────────────
    ext_tbl = _find_section(soup, "Browser Extensions")
    browser_extensions = []
    if ext_tbl:
        for row in _table_rows(ext_tbl):
            if row and row[0] not in ("Browser", ""):
                browser_extensions.append({
                    "browser": row[0],
                    "id":      row[1] if len(row) > 1 else "",
                })

    # ── Local Admin Accounts (Section 7) ──────────────────────────────────
    admin_tbl = _find_section(soup, "Local Administrator")
    admin_accounts = []
    if admin_tbl:
        for row in _table_rows(admin_tbl):
            if row and row[0] not in ("Name", ""):
                admin_accounts.append(row[0])

    # ── All Local Users (Section 7a) ──────────────────────────────────────
    all_users_tbl = _find_section(soup, "All Local User Accounts")
    all_users = []
    if all_users_tbl:
        for row in _table_rows(all_users_tbl):
            if row and row[0] not in ("Name", ""):
                all_users.append({
                    "name":             row[0],
                    "enabled":          row[1] if len(row) > 1 else "",
                    "pwd_never_expires": row[6] if len(row) > 6 else "",
                })

    # ── Scheduled Tasks (Section 22) ──────────────────────────────────────
    tasks_tbl = _find_section(soup, "Scheduled Tasks")
    scheduled_tasks = []
    if tasks_tbl:
        for row in _table_rows(tasks_tbl):
            if row and row[0] not in ("TaskName", ""):
                scheduled_tasks.append({
                    "name":  row[0],
                    "path":  row[1] if len(row) > 1 else "",
                    "state": row[2] if len(row) > 2 else "",
                })

    raw_data = {
        "hostname":              hostname,
        "os":                    os_name,
        "os_version":            os_version,
        "cpu":                   cpu,
        "ram":                   ram,
        "bios":                  bios,
        "ip":                    ip_address,
        "firewall":              str(firewall_enabled),
        "encryption":            str(encryption_enabled),
        "antivirus":             str(antivirus_installed),
        "antivirus_realtime":    str(antivirus_realtime),
        "antivirus_tamper":      str(antivirus_tamper),
        "secure_boot":           str(secure_boot_enabled),
        "tpm":                   str(tpm_present),
        "pending_updates":       str(pending_updates),
        "last_patch":            str(last_patch_date),
        "pass_max_days":         str(pass_max_days),
        "pass_min_len":          str(pass_min_len),
        "lockout_threshold":     str(lockout_threshold),
        "usb_storage_enabled":   str(usb_storage_enabled),
        "screen_lock_enabled":   str(screen_lock_enabled),
        "anydesk":               str(anydesk_running),
        "teamviewer":            str(teamviewer_running),
        "rdp":                   str(rdp_open),
        "chrome_remote_desktop": str(chrome_remote_desktop),
        "running_services":      services,
        "open_ports":            open_ports,
        "installed_software":    installed_sw,
        "browser_extensions":    browser_extensions,
        "admin_accounts":        admin_accounts,
        "all_users":             all_users,
        "scheduled_tasks":       scheduled_tasks,
        "installed_patches":     installed_patches,
    }

    return {
        # Identity
        "hostname":              hostname,
        "os_type":               "windows",
        "os_name":               os_name,
        "os_version":            os_version,
        "architecture":          "x86_64",
        "ip_address":            ip_address,
        "report_date":           report_date,
        "report_file":           str(filepath),
        # Hardware
        "cpu":                   cpu,
        "ram":                   ram,
        "bios_version":          bios,
        # Security
        "firewall_enabled":      firewall_enabled,
        "encryption_enabled":    encryption_enabled,
        "antivirus_installed":   antivirus_installed,
        "antivirus_name":        "Windows Defender",
        "antivirus_realtime":    antivirus_realtime,
        "antivirus_updated_at":  antivirus_updated_at,
        "antivirus_tamper":      antivirus_tamper,
        "secure_boot_enabled":   secure_boot_enabled,
        "tpm_present":           tpm_present,
        "ssh_enabled":           None,
        "auditd_enabled":        None,
        "passwordless_sudo":     None,
        "sip_enabled":           None,
        "gatekeeper_enabled":    None,
        # New fields
        "usb_storage_enabled":   usb_storage_enabled,
        "screen_lock_enabled":   screen_lock_enabled,
        "chrome_remote_desktop": chrome_remote_desktop,
        # Updates
        "pending_updates":       pending_updates,
        "last_patch_date":       last_patch_date,
        # Password policy
        "pass_max_days":         pass_max_days,
        "pass_min_days":         pass_min_days,
        "pass_min_len":          pass_min_len,
        "lockout_threshold":     lockout_threshold,
        # Remote access
        "anydesk_running":       anydesk_running,
        "teamviewer_running":    teamviewer_running,
        "rdp_open":              rdp_open,
        # Raw snapshot
        "raw_data":              raw_data,
    }
